version: '3.5'

services:
  db:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./server/db:/var/lib/mysql

  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server/src:/src/app/server/src
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    command: [sh, -c, "npm install && npm start"]

  client:
    container_name: react-client
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client/src:/src/app/client/src
      - ./client/public:/src/app/client/public
    ports:
      - 3000:3000
    depends_on:
      - server
    command: [sh, -c, "npm install && npm start"]