version: '3.5'

services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server/src:/src/app/server/src
    ports:
      - 8080:8080
    command: [sh, -c, "npm install && npm start"]

  client:
    container_name: react-client
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client/src:/src/app/client/src
      - ./client/public:/src/app/client/public
    ports:
      - 3000:3000
    depends_on:
      - server
    command: [sh, -c, "npm install && npm start"]