FROM node:alpine
RUN mkdir -p /usr/src/app/client
WORKDIR /usr/src/app/client
COPY client /usr/src/app/client
RUN npm install
RUN npm run build

FROM nginx:latest

# For when I setup the production server later
#RUN rm -rf /etc/nginx/conf.d 
#COPY conf /etc/nginx

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]